apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - otel-collector-configmap.yaml
  - otel-collector-deployment.yaml
  - otel-collector-service.yaml
  - lgtm-deployment.yaml
  - lgtm-service.yaml
  - grafana-ingress.yaml
  - otlp-ingress.yaml
