apiVersion: v1
kind: Service
metadata:
  name: lgtm
  namespace: observability
  labels:
    app: lgtm
spec:
  selector:
    app: lgtm
  ports:
    - name: grafana
      port: 3000
      targetPort: grafana
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
